export enum KYCStatus {
  NOT_SUBMITTED = 'NOT_SUBMITTED',
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED'
}

export enum CardType {
  VIRTUAL = 'VIRTUAL',
  PHYSICAL = 'PHYSICAL'
}

export enum CardStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  CANCELLED = 'CANCELLED'
}

export enum PhysicalCardStatus {
  ORDERED = 'ORDERED',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  ACTIVATED = 'ACTIVATED'
}

export enum TransactionType {
  CARD_PURCHASE = 'CARD_PURCHASE',
  CARD_TOPUP = 'CARD_TOPUP',
  CARD_REFUND = 'CARD_REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  DEPOSIT = 'DEPOSIT',
  TRANSFER = 'TRANSFER',
  FEE = 'FEE'
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  SETTLED = 'SETTLED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED'
}

export enum TransactionCategory {
  FOOD = 'FOOD',
  TRANSPORT = 'TRANSPORT',
  SHOPPING = 'SHOPPING',
  ENTERTAINMENT = 'ENTERTAINMENT',
  TRAVEL = 'TRAVEL',
  UTILITIES = 'UTILITIES',
  HEALTH = 'HEALTH',
  SERVICES = 'SERVICES',
  TRANSFER = 'TRANSFER',
  CRYPTO = 'CRYPTO',
  OTHER = 'OTHER'
}
